name: Pytest

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    # NOTE: You CAN'T have the `paths` key here!!
    #    if you do, and the PR doesn't trigger this,
    #    you won't be able to merge it.
    #   (Apart of dependabot updates. See the
    #    README.md in this dir for more details...)

## If a older test-suite job is running, kill it:
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

## Minimal Permissions:
permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      ## Setup Python:
      - name: Setup Python
        uses: ./.github/workflows/composite-setup-python
        with:
          # Tox will install them into it's own env:
          install-packages: False

      ## Install Tox:
      - name: Install Tox
        run: python3 -m pip install tox

      ## Run Pytest:
      - name: Run Pytest
        run: make test
